"""
Módulo de Help e Tela - Funções para exibição de ajuda e interface.

Este módulo contém todas as funções responsáveis por exibir:
- Banner do programa
- Help geral e por comando
- Mensagens de sucesso/erro/aviso
"""


def print_banner() -> None:
    """
    Exibe o banner ASCII artístico do PDF-cli.

    Banner conforme ESPECIFICACOES-FASE-2-EXTRACAO-EDICAO-TEXTO.md
    Este banner deve ser exibido obrigatoriamente ao executar o programa sem parâmetros.
    """
    banner = """┏━┓╺┳┓┏━╸  ┏━╸╻  ╻
┣━┛ ┃┃┣╸╺━╸┃  ┃  ┃
╹  ╺┻┛╹    ┗━╸┗━╸╹
2025 ⓒ Eduardo Alcantara
Made With Perplexity & Cursor
Ferramenta CLI para automacaão de edicao de arquivos PDF"""
    print(banner)


def print_success(message: str) -> None:
    """Imprime mensagem de sucesso."""
    print(f"[OK] {message}")


def print_error(message: str) -> None:
    """Imprime mensagem de erro."""
    import sys
    print(f"[ERRO] {message}", file=sys.stderr)


def print_warning(message: str) -> None:
    """Imprime mensagem de aviso."""
    print(f"[AVISO] {message}")


def print_help_general() -> None:
    """Exibe o help geral do programa."""
    print()
    print("COMANDOS DISPONIVEIS:")
    print("  export-text        - Extrai apenas textos do PDF para JSON (alias)")
    print("  export-objects     - Extrai objetos do PDF para JSON")
    print("  export-images      - Extrai imagens do PDF como arquivos PNG/JPG")
    print("  list-fonts         - Lista todas as fontes e variantes usadas no PDF")
    print("  edit-text          - Edita objeto de texto")
    print("  edit-table         - Edita tabela")
    print("  replace-image      - Substitui imagem")
    print("  insert-object      - Insere novo objeto")
    print("  restore-from-json  - Restaura PDF via JSON")
    print("  edit-metadata      - Edita metadados")
    print("  merge              - Une multiplos PDFs")
    print("  delete-pages       - Exclui paginas")
    print("  split              - Divide PDF em multiplos arquivos")
    print("  md-to-pdf          - Converte arquivo Markdown (.md) para PDF")
    print()
    print("OPCOES GLOBAIS:")
    print("  --help, -h         - Exibe esta mensagem de ajuda")
    print("  --version, -v      - Exibe a versao do programa")
    print()
    print("OPCOES EXTRAS (disponiveis em varios comandos):")
    print("  --verbose, -l      - Exibe informacoes detalhadas sobre a operacao (log)")
    print("  --force, -q        - Executa operacao sem criar backup ou pedir confirmacao (quiet)")
    print("  --output, -o       - Especifica arquivo ou diretorio de saida (alguns comandos)")
    print("  --format, -f       - Especifica formato de saida (png, jpg, etc.)")
    print("  --types, -t        - Especifica tipos de objetos (text, image, etc.)")
    print()
    print("NOTA: Nem todas as opcoes extras estao disponiveis em todos os comandos.")
    print("      Use 'pdf-cli --help <comando>' para ver opcoes especificas de cada comando.")
    print()
    print("Para ajuda detalhada de um comando:")
    print("  pdf-cli --help <comando>")
    print("  pdf-cli <comando> --help")


def print_help_export_text() -> None:
    """Exibe help detalhado do comando export-text."""
    print()
    print("COMANDO: export-text")
    print()
    print("DESCRICAO:")
    print("  Extrai e exporta apenas textos do PDF para JSON.")
    print("  Este comando e um alias para 'export-objects --types text'.")
    print()
    print("SINTAXE:")
    print("  pdf-cli export-text <arquivo_entrada.pdf> <arquivo_saida.json> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - Exemplo: C:/documentos/boleto.pdf ou ./examples/boleto.pdf")
    print()
    print("  <arquivo_saida.json>")
    print("    - Caminho completo incluindo o nome do arquivo JSON de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print("    - Exemplo: C:/documentos/boleto_textos.json")
    print()
    print("OPCOES:")
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas sobre a extracao")
    print("    - Mostra estatisticas por pagina")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Extrair textos de um boleto")
    print("  pdf-cli export-text boleto.pdf boleto_textos.json")
    print()
    print("  # Extrair textos com informacoes detalhadas")
    print("  pdf-cli export-text boleto.pdf boleto_textos.json --verbose")
    print("  pdf-cli export-text boleto.pdf boleto_textos.json -l")
    print()
    print("ESTRUTURA DO JSON GERADO:")
    print("  O JSON e organizado por paginas:")
    print("  {")
    print("    \"0\": {")
    print("      \"text\": [")
    print("        {")
    print("          \"id\": \"abc123...\",")
    print("          \"page\": 0,")
    print("          \"content\": \"Texto extraido\",")
    print("          \"x\": 56.0,")
    print("          \"y\": 792.0,")
    print("          \"width\": 120.5,")
    print("          \"height\": 12.0,")
    print("          \"font_name\": \"ArialMT\",")
    print("          \"font_size\": 12,")
    print("          \"color\": \"#000000\"")
    print("        }")
    print("      ]")
    print("    }")
    print("  }")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com timestamp e hash.")
    print()
    print("LIMITACOES:")
    print("  - PDFs escaneados nao terao texto extraido")
    print("  - Textos em colunas complexas podem ser extraidos fora de ordem")
    print("  - Tabelas sao extraidas como textos simples, sem estrutura preservada")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects, export-images, list-fonts")
    print()


def print_help_export_objects() -> None:
    """Exibe help detalhado do comando export-objects."""
    print()
    print("COMANDO: export-objects")
    print()
    print("DESCRICAO:")
    print("  Extrai e exporta objetos do PDF para JSON com metadados completos.")
    print("  Este comando extrai diferentes tipos de objetos do PDF (textos, imagens,")
    print("  links, anotacoes, etc.) e os exporta para um arquivo JSON estruturado,")
    print("  preservando todas as informacoes de formatacao, posicao e metadados.")
    print()
    print("SINTAXE:")
    print("  pdf-cli export-objects <arquivo_entrada.pdf> <arquivo_saida.json> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - Exemplo: C:/documentos/boleto.pdf ou ./examples/boleto.pdf")
    print()
    print("  <arquivo_saida.json>")
    print("    - Caminho completo incluindo o nome do arquivo JSON de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print("    - Exemplo: C:/documentos/boleto_objetos.json")
    print()
    print("OPCOES:")
    print("  --types, -t <tipos>")
    print("    - Tipos de objetos a exportar separados por virgula")
    print("    - Tipos: text,image,link,annotation,table,formfield,graphic,layer,filter")
    print("    - Padrao: todos os tipos")
    print("    - Exemplo: --types text,image")
    print()
    print("  --include-fonts")
    print("    - Inclui informacoes detalhadas de fontes no JSON exportado")
    print("    - Adiciona secao _fonts com detalhes de todas as fontes")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas sobre a extracao")
    print("    - Mostra estatisticas por tipo e pagina")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Exportar todos os objetos de um boleto")
    print("  pdf-cli export-objects boleto.pdf boleto_objetos.json")
    print()
    print("  # Exportar apenas textos e imagens")
    print("  pdf-cli export-objects boleto.pdf boleto_objetos.json --types text,image")
    print()
    print("  # Exportar com informacoes de fontes")
    print("  pdf-cli export-objects boleto.pdf boleto_objetos.json --include-fonts")
    print()
    print("  # Exportar apenas links e anotacoes")
    print("  pdf-cli export-objects despacho.pdf despacho_links.json --types link,annotation --verbose")
    print()
    print("  # Exportar tudo com estatisticas detalhadas")
    print("  pdf-cli export-objects contracheque.pdf contracheque_completo.json --include-fonts --verbose")
    print()
    print("ESTRUTURA DO JSON GERADO:")
    print("  O JSON e organizado por paginas:")
    print("  {")
    print("    \"0\": {")
    print("      \"text\": [...],")
    print("      \"image\": [...],")
    print("      \"link\": [...]")
    print("    },")
    print("    \"_fonts\": {")
    print("      \"total_fonts\": 3,")
    print("      \"fonts\": [...]")
    print("    }")
    print("  }")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com timestamp, parametros e estatisticas.")
    print()
    print("LIMITACOES:")
    print("  - Deteccao de tabelas e limitada (funcionalidade completa na fase final)")
    print("  - PDFs escaneados nao terao textos extraidos automaticamente")
    print("  - Objetos complexos (graficos, camadas) podem nao ser totalmente reconhecidos")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-text, export-images, list-fonts, restore-from-json")
    print()


def print_help_export_images() -> None:
    """Exibe help detalhado do comando export-images."""
    print()
    print("COMANDO: export-images")
    print()
    print("DESCRICAO:")
    print("  Extrai todas as imagens do PDF e salva como arquivos de imagem reais (PNG ou JPG).")
    print("  Diferente de 'export-objects --types image' que exporta apenas metadados em JSON,")
    print("  este comando salva as imagens como arquivos de imagem reais em um diretorio.")
    print()
    print("SINTAXE:")
    print("  pdf-cli export-images <arquivo_entrada.pdf> <diretorio_saida> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - Exemplo: C:/documentos/boleto.pdf ou ./examples/boleto.pdf")
    print()
    print("  <diretorio_saida>")
    print("    - Diretorio onde as imagens serao salvas (sera criado se nao existir)")
    print("    - IMPORTANTE: Deve ser um diretorio diferente do arquivo de entrada")
    print("    - Exemplo: C:/documentos/imagens/ ou ./imagens_extraidas/")
    print()
    print("OPCOES:")
    print("  --format, -f <formato>")
    print("    - Formato de saida: png (padrao) ou jpg")
    print("    - png: Formato PNG (sem perda de qualidade)")
    print("    - jpg: Formato JPEG (menor tamanho, perda de qualidade)")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas sobre cada imagem extraida")
    print("    - Mostra dimensoes e caminhos dos arquivos salvos")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Extrair todas as imagens como PNG (padrao)")
    print("  pdf-cli export-images boleto.pdf imagens_extraidas/")
    print()
    print("  # Extrair imagens como JPG")
    print("  pdf-cli export-images boleto.pdf imagens_jpg/ --format jpg")
    print()
    print("  # Extrair com informacoes detalhadas")
    print("  pdf-cli export-images boleto.pdf imagens/ --verbose")
    print()
    print("ESTRUTURA DE SAIDA:")
    print("  As imagens sao nomeadas como: imagem_<pagina>_<indice>.<extensao>")
    print("  - Pagina: numero da pagina (0-indexed)")
    print("  - Indice: ordem da imagem na pagina (1, 2, 3...)")
    print("  - Extensao: png ou jpg conforme --format")
    print()
    print("  Exemplos de nomes gerados:")
    print("  - imagem_0_1.png  (primeira imagem da primeira pagina)")
    print("  - imagem_0_2.png  (segunda imagem da primeira pagina)")
    print("  - imagem_1_1.jpg  (primeira imagem da segunda pagina)")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com lista de arquivos salvos e estatisticas.")
    print()
    print("LIMITACOES:")
    print("  - Imagens muito grandes podem levar tempo para processar")
    print("  - Qualidade original do PDF pode afetar a qualidade das imagens extraidas")
    print("  - Imagens em formato vetorial podem ser convertidas para raster")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects, replace-image, insert-object")
    print()


def print_help_list_fonts() -> None:
    """Exibe help detalhado do comando list-fonts."""
    print()
    print("COMANDO: list-fonts")
    print()
    print("DESCRICAO:")
    print("  Lista todas as fontes e suas variantes usadas no PDF.")
    print("  Este comando analisa o PDF e identifica todas as fontes utilizadas, mostrando")
    print("  informacoes detalhadas sobre cada uma, incluindo variantes, se esta embeddada,")
    print("  onde e como e usada no documento.")
    print()
    print("SINTAXE:")
    print("  pdf-cli list-fonts <arquivo_entrada.pdf> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - Exemplo: C:/documentos/boleto.pdf ou ./examples/boleto.pdf")
    print()
    print("OPCOES:")
    print("  --output, -o <arquivo.json>")
    print("    - Salva a lista de fontes em um arquivo JSON (opcional)")
    print("    - Exemplo: --output fontes_boleto.json")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas (encoding, xref, etc.)")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Listar todas as fontes de um boleto")
    print("  pdf-cli list-fonts boleto.pdf")
    print()
    print("  # Listar fontes e salvar em JSON")
    print("  pdf-cli list-fonts boleto.pdf --output fontes_boleto.json")
    print()
    print("  # Listar com informacoes detalhadas")
    print("  pdf-cli list-fonts boleto.pdf --verbose")
    print()
    print("INFORMACOES EXIBIDAS:")
    print("  - Nome da fonte (normalizado, sem prefixos de subset)")
    print("  - Variantes detectadas (Bold, Italic, Narrow, Condensed, Light, Black)")
    print("  - Status de embeddagem (EMBEDDED ou NAO EMBEDDED)")
    print("  - Estatisticas de uso (numero de ocorrencias, paginas, tamanhos)")
    print()
    print("IMPORTANTE PARA EDICAO DE TEXTO:")
    print("  Se voce planeja editar textos com 'edit-text', fontes nao embeddadas precisam")
    print("  estar instaladas no seu sistema operacional, caso contrario o sistema pode usar")
    print("  fontes similares que podem alterar a aparencia do documento.")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects --include-fonts, edit-text")
    print()


def print_help_edit_text() -> None:
    """Exibe help detalhado do comando edit-text."""
    print()
    print("COMANDO: edit-text")
    print()
    print("DESCRICAO:")
    print("  Edita um ou mais objetos de texto no PDF, substituindo conteudo, alterando")
    print("  posicao, fonte, cor, tamanho e outras propriedades. Preserva a aparencia")
    print("  visual original quando possivel, utilizando fontes embeddadas ou do sistema.")
    print()
    print("SINTAXE:")
    print("  pdf-cli edit-text <arquivo_entrada.pdf> <arquivo_saida.pdf> --new-content \"texto\" [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de saida")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print()
    print("  --new-content <texto>")
    print("    - OBRIGATORIO: Novo conteudo do texto a ser inserido")
    print("    - Se --content for especificado, substitui apenas a parte correspondente")
    print()
    print("OPCOES DE SELECAO DE OBJETO:")
    print("  --id <id_objeto>")
    print("    - ID unico do objeto de texto (obtido via export-objects)")
    print("    - Exemplo: --id abc123def456")
    print()
    print("  --content <texto_busca>")
    print("    - Busca texto que contem este termo (substitui parcialmente se for substring)")
    print("    - Se usado com --all-occurrences, edita todas as ocorrencias")
    print()
    print("OPCOES DE FORMATACAO:")
    print("  --align <direcao>")
    print("    - Alinhamento do texto: left, center, right")
    print()
    print("  --pad")
    print("    - Adiciona padding para preservar largura visual do bloco original")
    print()
    print("  --x <coordenada>")
    print("    - Nova coordenada X (sobrescreve posicao original)")
    print()
    print("  --y <coordenada>")
    print("    - Nova coordenada Y (sobrescreve posicao original)")
    print()
    print("  --font-name <nome>")
    print("    - Nome da fonte a ser usada (ex: ArialMT, TimesNewRoman-Bold)")
    print()
    print("  --font-size <tamanho>")
    print("    - Tamanho da fonte em pontos (ex: 12, 14, 18)")
    print()
    print("  --color <cor_hex>")
    print("    - Cor do texto em hexadecimal (ex: #000000, #FF0000)")
    print()
    print("  --rotation <graus>")
    print("    - Rotacao do texto em graus (ex: 0, 90, 180, 270)")
    print()
    print("OPCOES AVANCADAS:")
    print("  --all-occurrences")
    print("    - Edita todas as ocorrencias do texto de busca no PDF")
    print("    - Exibe feedback detalhado de cada ocorrencia editada")
    print()
    print("  --prefer-engine <engine>")
    print("    - Engine preferido: pymupdf (padrao) ou pypdf")
    print()
    print("  --force, -q")
    print("    - Executa sem criar backup ou pedir confirmacao")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas sobre a operacao")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Editar texto por ID")
    print("  pdf-cli edit-text boleto.pdf boleto_editado.pdf --id abc123 --new-content \"Novo Texto\"")
    print()
    print("  # Substituir texto buscando conteudo")
    print("  pdf-cli edit-text boleto.pdf boleto_editado.pdf --content \"ALCANTARA\" --new-content \"ALCANTARA\"")
    print()
    print("  # Editar todas as ocorrencias de um texto")
    print("  pdf-cli edit-text boleto.pdf boleto_editado.pdf --content \"Nome\" --new-content \"Nome Completo\" --all-occurrences")
    print()
    print("  # Editar com nova fonte e cor")
    print("  pdf-cli edit-text documento.pdf documento_editado.pdf --id xyz789 --new-content \"Destaque\" --font-name \"Arial-Bold\" --font-size 16 --color \"#FF0000\"")
    print()
    print("  # Editar centralizando e com padding")
    print("  pdf-cli edit-text titulo.pdf titulo_editado.pdf --content \"Titulo\" --new-content \"Novo Titulo\" --align center --pad")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com detalhes de cada edicao:")
    print("  - ID do objeto modificado")
    print("  - Conteudo antes e depois")
    print("  - Fonte original e usada")
    print("  - Deteccao de fallback de fonte")
    print()
    print("LIMITACOES:")
    print("  - Fontes nao embeddadas precisam estar instaladas no sistema operacional")
    print("  - Se a fonte nao for encontrada, o sistema pode usar uma similar (fallback)")
    print("  - Textos muito longos podem ultrapassar limites visuais do bloco original")
    print("  - PDFs escaneados nao podem ter textos editados diretamente")
    print()
    print("AVISOS IMPORTANTES:")
    print("  - O sistema avisara se fontes necessarias nao estao disponiveis")
    print("  - Use --all-occurrences com cuidado em PDFs grandes (pode demorar)")
    print("  - Sempre verifique o PDF de saida antes de sobrescrever o original")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects, export-text, list-fonts")
    print()


def print_help_edit_table() -> None:
    """Exibe help detalhado do comando edit-table."""
    print()
    print("COMANDO: edit-table")
    print()
    print("DESCRICAO:")
    print("  Edita uma celula ou cabecalho de tabela no PDF. Esta funcionalidade requer")
    print("  deteccao de estrutura de tabelas, que sera implementada em fase futura.")
    print()
    print("SINTAXE:")
    print("  pdf-cli edit-table <arquivo_entrada.pdf> <arquivo_saida.pdf> --table-id <id> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print()
    print("  --table-id <id>")
    print("    - ID unico da tabela (obtido via export-objects)")
    print()
    print("OPCOES:")
    print("  --row <numero>")
    print("    - Indice da linha (0-indexed)")
    print()
    print("  --col <numero>")
    print("    - Indice da coluna (0-indexed)")
    print()
    print("  --value <novo_valor>")
    print("    - Novo valor da celula")
    print()
    print("  --header <novo_cabecalho>")
    print("    - Novo cabecalho (se --row nao especificado)")
    print()
    print("  --force, -q")
    print("    - Executa sem criar backup")
    print()
    print("LIMITACOES:")
    print("  - Esta funcionalidade ainda nao esta implementada")
    print("  - Edicao de tabelas requer algoritmo de deteccao de estrutura de tabelas")
    print("  - Esta funcionalidade sera implementada em fase futura do projeto")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects, restore-from-json")
    print()


def print_help_replace_image() -> None:
    """Exibe help detalhado do comando replace-image."""
    print()
    print("COMANDO: replace-image")
    print()
    print("DESCRICAO:")
    print("  Substitui uma imagem existente no PDF por uma nova imagem de arquivo.")
    print("  A nova imagem e redimensionada para caber no espaco da imagem original.")
    print("  E possivel aplicar filtros como grayscale ou invert antes da substituicao.")
    print()
    print("SINTAXE:")
    print("  pdf-cli replace-image <arquivo_entrada.pdf> <arquivo_saida.pdf> --image-id <id> --src <arquivo_imagem> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de saida")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print()
    print("  --image-id <id>")
    print("    - ID unico da imagem a ser substituida (obtido via export-objects)")
    print("    - Exemplo: --image-id img-abc123def456")
    print()
    print("  --src <arquivo_imagem>")
    print("    - Caminho para o arquivo de imagem de substituicao (PNG, JPG, etc.)")
    print("    - Exemplo: --src ./nova_logo.png")
    print()
    print("OPCOES:")
    print("  --filter <tipo>")
    print("    - Tipo de filtro a aplicar na imagem:")
    print("      - grayscale: Converte para tons de cinza")
    print("      - invert: Inverte as cores")
    print("    - Exemplo: --filter grayscale")
    print()
    print("  --force, -q")
    print("    - Executa sem criar backup ou pedir confirmacao")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas sobre a substituicao")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Substituir logo por novo arquivo")
    print("  pdf-cli replace-image documento.pdf documento_novo.pdf --image-id img-123 --src ./novo_logo.png")
    print()
    print("  # Substituir e aplicar filtro grayscale")
    print("  pdf-cli replace-image foto.pdf foto_pb.pdf --image-id img-456 --src ./nova_foto.jpg --filter grayscale")
    print()
    print("  # Substituir com inversao de cores")
    print("  pdf-cli replace-image grafico.pdf grafico_invertido.pdf --image-id img-789 --src ./grafico.png --filter invert")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - ID da imagem substituida")
    print("  - Caminho da nova imagem")
    print("  - Filtro aplicado (se houver)")
    print("  - Dimensoes da imagem original e nova")
    print()
    print("LIMITACOES:")
    print("  - A nova imagem e redimensionada para caber no espaco da original")
    print("  - Imagens muito diferentes em proporcao podem ficar distorcidas")
    print("  - Formatos suportados: PNG, JPG, JPEG")
    print("  - Filtros requerem biblioteca PIL/Pillow instalada")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-images, export-objects, insert-object")
    print()


def print_help_insert_object() -> None:
    """Exibe help detalhado do comando insert-object."""
    print()
    print("COMANDO: insert-object")
    print()
    print("DESCRICAO:")
    print("  Insere um novo objeto (texto ou imagem) no PDF em uma posicao especificada.")
    print("  O objeto e inserido em uma pagina existente do PDF.")
    print()
    print("SINTAXE:")
    print("  pdf-cli insert-object <arquivo_entrada.pdf> <arquivo_saida.pdf> --type <tipo> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de saida")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print()
    print("  --type <tipo>")
    print("    - Tipo de objeto a inserir: text ou image")
    print()
    print("OPCOES PARA OBJETOS DE TEXTO (--type text):")
    print("  --page <numero>")
    print("    - Numero da pagina onde inserir (0-indexed, primeira pagina e 0)")
    print()
    print("  --content <texto>")
    print("    - Texto a ser inserido")
    print()
    print("  --x <coordenada>")
    print("    - Coordenada X da posicao")
    print()
    print("  --y <coordenada>")
    print("    - Coordenada Y da posicao")
    print()
    print("  --font-name <nome>")
    print("    - Nome da fonte (padrao: helv)")
    print()
    print("  --font-size <tamanho>")
    print("    - Tamanho da fonte em pontos (padrao: 12)")
    print()
    print("  --color <cor_hex>")
    print("    - Cor do texto em hexadecimal (padrao: #000000)")
    print()
    print("  --rotation <graus>")
    print("    - Rotacao em graus (padrao: 0)")
    print()
    print("OPCOES PARA OBJETOS DE IMAGEM (--type image):")
    print("  --page <numero>")
    print("    - Numero da pagina onde inserir (0-indexed)")
    print()
    print("  --src <arquivo_imagem>")
    print("    - Caminho para o arquivo de imagem")
    print()
    print("  --x <coordenada>")
    print("    - Coordenada X da posicao")
    print()
    print("  --y <coordenada>")
    print("    - Coordenada Y da posicao")
    print()
    print("  --width <largura>")
    print("    - Largura da imagem (padrao: 100)")
    print()
    print("  --height <altura>")
    print("    - Altura da imagem (padrao: 100)")
    print()
    print("OPCOES GERAIS:")
    print("  --force, -q")
    print("    - Executa sem criar backup")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Inserir texto na primeira pagina")
    print("  pdf-cli insert-object documento.pdf documento_com_texto.pdf --type text --page 0 --content \"Novo Texto\" --x 100 --y 200 --font-size 14")
    print()
    print("  # Inserir imagem na segunda pagina")
    print("  pdf-cli insert-object relatorio.pdf relatorio_com_logo.pdf --type image --page 1 --src ./logo.png --x 50 --y 50 --width 150 --height 50")
    print()
    print("LIMITACOES:")
    print("  - Apenas objetos do tipo 'text' e 'image' estao totalmente implementados")
    print("  - Objetos complexos (tabelas, links, graficos) ainda nao sao suportados")
    print("  - Coordenadas sao absolutas (nao relativas ao conteudo existente)")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  edit-text, replace-image, export-objects")
    print()


def print_help_restore_from_json() -> None:
    """Exibe help detalhado do comando restore-from-json."""
    print()
    print("COMANDO: restore-from-json")
    print()
    print("DESCRICAO:")
    print("  Restaura ou reaplica alteracoes de um arquivo JSON ao PDF original.")
    print("  O JSON deve conter objetos editados (geralmente exportado previamente)")
    print("  com as modificacoes desejadas. Esta funcionalidade permite aplicar")
    print("  multiplas edicoes de uma vez usando um arquivo de configuracao JSON.")
    print()
    print("SINTAXE:")
    print("  pdf-cli restore-from-json <arquivo_original.pdf> <arquivo_json.json> <arquivo_saida.pdf> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_original.pdf>")
    print("    - Caminho para o PDF original (base para restaurar)")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de saida")
    print()
    print("  <arquivo_json.json>")
    print("    - Caminho para o arquivo JSON com objetos editados")
    print("    - Deve seguir estrutura de export-objects agrupada por pagina")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print()
    print("OPCOES:")
    print("  --force, -q")
    print("    - Executa sem criar backup ou pedir confirmacao")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas sobre cada alteracao aplicada")
    print()
    print("ESTRUTURA DO JSON ESPERADA:")
    print("  {")
    print("    \"0\": {")
    print("      \"text\": [")
    print("        {")
    print("          \"id\": \"abc123...\",")
    print("          \"content\": \"Texto editado\",")
    print("          \"page\": 0,")
    print("          \"font_name\": \"ArialMT\",")
    print("          \"font_size\": 12,")
    print("          \"color\": \"#000000\"")
    print("        }")
    print("      ]")
    print("    }")
    print("  }")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Restaurar PDF a partir de JSON editado")
    print("  pdf-cli restore-from-json original.pdf editado.json restaurado.pdf")
    print()
    print("  # Restaurar com informacoes detalhadas")
    print("  pdf-cli restore-from-json base.pdf modificacoes.json final.pdf --verbose")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - Numero de alteracoes aplicadas")
    print("  - Paginas modificadas")
    print("  - Tipos de objetos restaurados")
    print()
    print("LIMITACOES:")
    print("  - A restauracao de imagens ainda nao esta totalmente implementada")
    print("  - O JSON deve seguir exatamente a estrutura de export-objects")
    print("  - Objetos com ID inexistente no PDF original sao ignorados")
    print("  - Apenas objetos do tipo 'text' sao totalmente suportados")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects, edit-text")
    print()


def print_help_edit_metadata() -> None:
    """Exibe help detalhado do comando edit-metadata."""
    print()
    print("COMANDO: edit-metadata")
    print()
    print("DESCRICAO:")
    print("  Edita metadados do PDF como titulo, autor, assunto, palavras-chave, criador")
    print("  e produtor. Os metadados sao informacoes descritivas do documento que podem")
    print("  ser visualizadas em leitores de PDF e sistemas de gerenciamento de documentos.")
    print()
    print("SINTAXE:")
    print("  pdf-cli edit-metadata <arquivo_entrada.pdf> <arquivo_saida.pdf> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de saida")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print()
    print("OPCOES (pelo menos uma deve ser especificada):")
    print("  --title <titulo>")
    print("    - Novo titulo do documento")
    print()
    print("  --author <autor>")
    print("    - Novo autor do documento")
    print()
    print("  --subject <assunto>")
    print("    - Novo assunto/tema do documento")
    print()
    print("  --keywords <palavras>")
    print("    - Novas palavras-chave (separadas por virgula)")
    print("    - Exemplo: --keywords \"pdf,cliente,relatorio\"")
    print()
    print("  --creator <criador>")
    print("    - Aplicativo que criou o documento")
    print()
    print("  --producer <produtor>")
    print("    - Aplicativo que converteu o documento para PDF")
    print()
    print("OPCOES GERAIS:")
    print("  --force, -q")
    print("    - Executa sem criar backup")
    print()
    print("  --verbose, -l")
    print("    - Exibe metadados antes e depois da edicao")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Alterar titulo e autor")
    print("  pdf-cli edit-metadata documento.pdf documento_editado.pdf --title \"Novo Titulo\" --author \"Joao Silva\"")
    print()
    print("  # Adicionar palavras-chave")
    print("  pdf-cli edit-metadata relatorio.pdf relatorio_indexado.pdf --keywords \"financeiro,2025,trimestral\"")
    print()
    print("  # Atualizar todos os metadados")
    print("  pdf-cli edit-metadata arquivo.pdf arquivo_novo.pdf --title \"Documento\" --author \"Autor\" --subject \"Assunto\" --keywords \"tag1,tag2\"")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - Metadados antes da edicao")
    print("  - Metadados depois da edicao")
    print("  - Campos modificados")
    print()
    print("LIMITACOES:")
    print("  - Metadados nao afetam o conteudo visual do PDF")
    print("  - Alguns campos podem nao ser suportados por todos os leitores de PDF")
    print("  - Metadados existentes nao especificados sao preservados")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-objects (para ver metadados atuais)")
    print()


def print_help_merge() -> None:
    """Exibe help detalhado do comando merge."""
    print()
    print("COMANDO: merge")
    print()
    print("DESCRICAO:")
    print("  Une multiplos arquivos PDF em um unico documento. O comando concatena")
    print("  todos os PDFs informados em ordem, criando um novo arquivo com todas")
    print("  as paginas dos PDFs originais combinadas sequencialmente.")
    print()
    print("SINTAXE:")
    print("  pdf-cli merge <arquivo1.pdf> <arquivo2.pdf> [arquivo3.pdf ...] <arquivo_saida.pdf>")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo1.pdf> <arquivo2.pdf> ...")
    print("    - Dois ou mais arquivos PDF a serem unidos")
    print("    - Os PDFs serao concatenados na ordem especificada")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do PDF resultante")
    print("    - IMPORTANTE: Nao deve ser o mesmo que nenhum dos arquivos de entrada")
    print()
    print("OPCOES:")
    print("  --verbose, -l")
    print("    - Exibe informacoes sobre cada PDF sendo unido")
    print("    - Mostra numero de paginas de cada arquivo")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Unir dois PDFs")
    print("  pdf-cli merge documento1.pdf documento2.pdf resultado.pdf")
    print()
    print("  # Unir tres PDFs em ordem especifica")
    print("  pdf-cli merge capa.pdf conteudo.pdf anexos.pdf documento_completo.pdf")
    print()
    print("  # Unir multiplos PDFs com informacoes detalhadas")
    print("  pdf-cli merge parte1.pdf parte2.pdf parte3.pdf completo.pdf --verbose")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - Lista de arquivos unidos")
    print("  - Numero total de paginas do resultado")
    print("  - Numero de paginas de cada arquivo de entrada")
    print()
    print("LIMITACOES:")
    print("  - O arquivo de saida nao pode ser o mesmo que nenhum arquivo de entrada")
    print("  - PDFs protegidos com senha podem nao ser unidos corretamente")
    print("  - Metadados do PDF resultante sao baseados no primeiro PDF")
    print("  - Marcadores e links internos podem nao funcionar corretamente apos uniao")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  split, delete-pages")
    print()


def print_help_delete_pages() -> None:
    """Exibe help detalhado do comando delete-pages."""
    print()
    print("COMANDO: delete-pages")
    print()
    print("DESCRICAO:")
    print("  Exclui paginas especificas de um PDF. As paginas restantes sao mantidas")
    print("  em ordem. Esta e uma operacao destrutiva que requer confirmacao ou flag --force.")
    print()
    print("SINTAXE:")
    print("  pdf-cli delete-pages <arquivo_entrada.pdf> <arquivo_saida.pdf> --pages <numeros> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de saida")
    print()
    print("  <arquivo_saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print()
    print("  --pages <numeros>")
    print("    - Numeros das paginas a excluir (1-indexed)")
    print("    - Formato: \"1,3,5\" ou \"1-5\" ou \"1,3-5,10\"")
    print("    - Exemplo: --pages \"2,5,7\" ou --pages \"1-3\"")
    print()
    print("OPCOES:")
    print("  --force, -q")
    print("    - Executa sem criar backup ou pedir confirmacao")
    print("    - ATENCAO: Operacao destrutiva, use com cuidado")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes sobre paginas excluidas")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Excluir paginas especificas")
    print("  pdf-cli delete-pages documento.pdf documento_sem_pags.pdf --pages \"2,5,7\"")
    print()
    print("  # Excluir faixa de paginas")
    print("  pdf-cli delete-pages relatorio.pdf relatorio_editado.pdf --pages \"10-15\"")
    print()
    print("  # Excluir paginas mistas")
    print("  pdf-cli delete-pages arquivo.pdf arquivo_final.pdf --pages \"1,3-5,10\"")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - Paginas excluidas")
    print("  - Numero total de paginas antes e depois")
    print("  - Caminho do backup (se criado)")
    print()
    print("LIMITACOES:")
    print("  - Esta e uma operacao irreversivel sem backup")
    print("  - Links e referencias internas podem quebrar apos exclusao de paginas")
    print("  - Marcadores e sumarios podem ficar desatualizados")
    print("  - Numeracao de paginas mantida (nao renumera automaticamente)")
    print()
    print("AVISOS IMPORTANTES:")
    print("  - SEMPRE use --force com cuidado, pois nao cria backup automatico")
    print("  - Verifique o PDF de saida antes de sobrescrever o original")
    print("  - Backup automatico e criado por padrao (a menos que --force seja usado)")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  split, merge")
    print()


def print_help_md_to_pdf() -> None:
    """Exibe help detalhado do comando md-to-pdf."""
    print()
    print("COMANDO: md-to-pdf")
    print()
    print("DESCRICAO:")
    print("  Converte um arquivo Markdown (.md) para PDF mantendo a formatação visual.")
    print("  Suporta títulos, listas, tabelas, blocos de código, imagens locais e links.")
    print("  Utiliza CSS padrão amigável, mas permite CSS customizado via --css.")
    print()
    print("SINTAXE:")
    print("  pdf-cli md-to-pdf <entrada.md> <saida.pdf> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <entrada.md>")
    print("    - Caminho completo incluindo o nome do arquivo Markdown de entrada")
    print("    - Deve terminar com extensao .md")
    print("    - Exemplo: documento.md ou ./docs/manual.md")
    print()
    print("  <saida.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de saida")
    print("    - Deve terminar com extensao .pdf")
    print("    - IMPORTANTE: Deve ser diferente do arquivo de entrada")
    print("    - Exemplo: documento.pdf ou ./outputs/manual.pdf")
    print()
    print("OPCOES:")
    print("  --css <caminho.css>")
    print("    - Caminho para arquivo CSS customizado para estilização do PDF")
    print("    - Se nao especificado, usa CSS padrao amigavel")
    print("    - Exemplo: --css styles/custom.css")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes detalhadas durante a conversao")
    print("    - Mostra etapas: leitura, conversao MD->HTML, conversao HTML->PDF")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Conversao basica")
    print("  pdf-cli md-to-pdf README.md README.pdf")
    print()
    print("  # Conversao com CSS customizado")
    print("  pdf-cli md-to-pdf manual.md manual.pdf --css styles/custom.css")
    print()
    print("  # Conversao com informacoes detalhadas")
    print("  pdf-cli md-to-pdf documento.md documento.pdf --verbose")
    print()
    print("ESTRUTURA DO PDF GERADO:")
    print("  O PDF gerado tera formatação profissional com:")
    print("  - Margens adequadas (2cm)")
    print("  - Tipografia clara (fontes serifadas e monospace para codigo)")
    print("  - Cabeçalhos estilizados (H1-H6)")
    print("  - Blocos de codigo com fundo destacado")
    print("  - Tabelas com bordas e cabeçalhos destacados")
    print("  - Links clicaveis (quando possivel)")
    print()
    print("SUPORTE A MARKDOWN:")
    print("  - Titulos (H1-H6)")
    print("  - Texto formatado (negrito, italico, codigo inline)")
    print("  - Listas (ordenadas e nao ordenadas)")
    print("  - Blocos de codigo (com syntax highlighting quando disponivel)")
    print("  - Tabelas")
    print("  - Links")
    print("  - Imagens locais (se disponiveis no mesmo diretorio ou caminho relativo)")
    print("  - Imagens remotas (via URL)")
    print("  - Citacoes (blockquote)")
    print("  - Linhas horizontais")
    print()
    print("IMAGENS:")
    print("  - Imagens locais devem estar no mesmo diretorio do arquivo .md")
    print("    ou usar caminhos relativos corretos")
    print("  - Imagens remotas (URL) sao baixadas automaticamente")
    print("  - Formatos suportados: PNG, JPG, GIF, SVG")
    print()
    print("CSS PADRAO:")
    print("  O CSS padrao inclui:")
    print("  - Pagina A4 com margens de 2cm")
    print("  - Fontes DejaVu Sans (fallback para Arial, sans-serif)")
    print("  - Estilos para todos os elementos HTML comuns")
    print("  - Cores e espacamentos profissionais")
    print()
    print("BIBLIOTECAS DE CONVERSAO (MULTIPLATAFORMA):")
    print("  O comando detecta automaticamente a melhor biblioteca disponivel:")
    print("  - WeasyPrint (preferido): Melhor qualidade, funciona no Linux")
    print("    * Linux: Instale dependencias do sistema:")
    print("      sudo apt-get install python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0")
    print("    * Windows: Requer GTK instalado (consulte documentacao WeasyPrint)")
    print("  - xhtml2pdf (fallback): Portavel, funciona em Windows e Linux")
    print("    * Instalacao: pip install xhtml2pdf")
    print("    * Nao requer dependencias externas do sistema")
    print("  - O comando faz fallback automatico se WeasyPrint nao estiver disponivel")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - Arquivos de entrada e saida")
    print("  - Numero de paginas geradas")
    print("  - CSS usado (padrao ou customizado)")
    print("  - Erros (se houver)")
    print()
    print("LIMITACOES:")
    print("  - Markdown avancado (tabelas complexas, notas de rodape) pode ter suporte limitado")
    print("  - Imagens muito grandes podem afetar o tamanho do PDF")
    print("  - Links para secoes do documento podem nao funcionar")
    print("  - Algumas extensoes Markdown podem nao ser suportadas")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  export-text, export-objects (para converter PDF para texto/objetos)")
    print()


def print_help_split() -> None:
    """Exibe help detalhado do comando split."""
    print()
    print("COMANDO: split")
    print()
    print("DESCRICAO:")
    print("  Divide um PDF em multiplos arquivos conforme faixas de paginas especificadas.")
    print("  Cada faixa de paginas gera um novo arquivo PDF. E util para separar")
    print("  documentos grandes em partes menores ou extrair secoes especificas.")
    print()
    print("SINTAXE:")
    print("  pdf-cli split <arquivo_entrada.pdf> <prefixo_saida> --ranges <faixas> [opcoes]")
    print()
    print("ARGUMENTOS OBRIGATORIOS:")
    print("  <arquivo_entrada.pdf>")
    print("    - Caminho completo incluindo o nome do arquivo PDF de entrada")
    print()
    print("  <prefixo_saida>")
    print("    - Prefixo para os arquivos de saida")
    print("    - Os arquivos serao nomeados como: <prefixo>1.pdf, <prefixo>2.pdf, etc.")
    print("    - Exemplo: \"parte_\" gera \"parte_1.pdf\", \"parte_2.pdf\"")
    print()
    print("  --ranges <faixas>")
    print("    - Faixas de paginas para cada arquivo (1-indexed)")
    print("    - Formato: \"1-3,4-6,7-10\" (cada faixa gera um arquivo)")
    print("    - Exemplo: --ranges \"1-5,6-10,11-15\" gera 3 arquivos")
    print()
    print("OPCOES:")
    print("  --force, -q")
    print("    - Executa sem criar backup")
    print()
    print("  --verbose, -l")
    print("    - Exibe informacoes sobre cada arquivo criado")
    print()
    print("EXEMPLOS:")
    print()
    print("  # Dividir PDF em tres partes")
    print("  pdf-cli split documento.pdf parte_ --ranges \"1-10,11-20,21-30\"")
    print("  # Gera: parte_1.pdf (pags 1-10), parte_2.pdf (pags 11-20), parte_3.pdf (pags 21-30)")
    print()
    print("  # Dividir em capitulos")
    print("  pdf-cli split livro.pdf capitulo_ --ranges \"1-15,16-35,36-50\"")
    print()
    print("  # Dividir com paginas unicas e faixas")
    print("  pdf-cli split relatorio.pdf secao_ --ranges \"1,2-5,6-10,11\"")
    print()
    print("LOGS:")
    print("  Operacoes registradas em 'logs/' com:")
    print("  - Faixas de paginas processadas")
    print("  - Arquivos gerados e seus caminhos")
    print("  - Numero total de arquivos criados")
    print()
    print("LIMITACOES:")
    print("  - Faixas de paginas nao podem se sobrepor")
    print("  - Paginas fora das faixas especificadas nao sao incluídas em nenhum arquivo")
    print("  - Links e referencias internas podem nao funcionar corretamente nos PDFs divididos")
    print("  - Metadados sao copiados para cada arquivo gerado")
    print()
    print("COMANDOS RELACIONADOS:")
    print("  merge, delete-pages")
    print()
